### ISSUE TITLE
Matlab production server adding file to archive

### ISSUE THREAD

**Issue by ketimaBU** [IanHuntress/GoldenGateReactionDesigner#6]
Hi, I  am using matlab server 2016a with node js ,I am trying to make it add a files dynamically to the deployable  project at run time, I don't have good experience with matlab.
I am noticing that you are using that so any help will be appreciated

**Comment by IanHuntress** [comment]
Unfortunately I will have very little to offer.
The main problem that I tinkered with in this project was the annoying communication between node and Matlab. The most simple solution I could find is located in Server.js line 48.
`        var child = spawn("matlab",["-nodisplay", "-nosplash", "-nodesktop", "-logfile", outputFile, "-r", "cd " + path.join(__dirname,"matlabOverhangFinder") + "; userSpreadsheet = '" + path.join(__dirname,"uploads",fName) + "'; Experimental_Driver_Jan2017(userSpreadsheet); exit;"],{}); 
`
Node creates a separate thread which runs matlab code in the command line. It uses the matlab -r flag to run an experiment-design script, and specifies an output text file where Node awaits the answers.

If you are intent on "dynamically" using the spawned matlab thread, you will likely need to communicate back and forth between node and the child. The docs for that are here: [https://nodejs.org/api/child_process.html#child_process_event_message](https://nodejs.org/api/child_process.html#child_process_event_message)
Regardless, you will probably need this: [https://www.mathworks.com/help/simulink/slref/addfile.html](https://www.mathworks.com/help/simulink/slref/addfile.html)
in order to call something like this:

`var myNodeChildJob = spawn("matlab",["-nodisplay", "-nosplash", "-nodesktop", "-logfile", outputFile, "-r", "addFile(project, file )"`

Good luck.

**Comment by ketimaBU** [comment]
Thank you so much i will give a try immediately 👍  🥇
